### ISSUE TITLE
Defer loading with use-package

### ISSUE THREAD

**Issue by andyleejordan** [justbur/evil-ediff#2]
Hi @justbur,

Do you know how to defer the loading of `evil-ediff` with `use-package`? I just don't know what `:bind` or `:mode` to use to defer it (since I don't want it bound or loaded with a file). I _think_ I'd need to `(use-package ediff :config (use-package evil-ediff))` but am not sure, as `evil-ediff` requires both `evil` and `ediff`, and I'd want it loaded on demand (long after `evil` is loaded). Do you think this is accomplishable?

**Comment by justbur** [comment]
Try this

``` elisp
(use-package ediff
  :defer t
  :config (require 'evil-ediff))
```

**Comment by justbur** [comment]
@andschwa did that work?

**Comment by andyleejordan** [comment]
Yes! Sorry for taking so long to get back to you.

``` t
(use-package ediff
  :defer t
  :config (use-package evil-ediff))
```

I was honestly surprised, since I expected ediff's bindings to longer be loaded; but it appears those auto-loads are added regardless. This worked great. Thanks @justbur!
