### ISSUE TITLE
More evil bindings?

### ISSUE THREAD

**Issue by Ambrevar** [justbur/evil-ediff#7]
I find the current bindings a tad too Emacs-ish:

`n/p` is Emacs-oriented, it's `j/k` in the vi world. They are the most used keys.
`j/k` is currently bound to `evil-ediff-scroll-up-1` / `evil-ediff-scroll-down-1`, which is usually bound to `C-e / C-y`. You don't need it that much in Ediff.

My suggestion is to remap as follows:
- `j` -> `C-e`
- `k` -> `C-y`
- `n` -> `j`
- `p` -> `k`

**Comment by justbur** [comment]
I like the suggestion. @TheBB any thoughts?

**Comment by TheBB** [comment]
I like it too, although I haven't used ediff so much that I really have a big opinion.

**Comment by Ambrevar** [comment]
I'm using it _a big lot_ these days! The key binding suggestion makes ediff a real bliss, especially when switching context, in my humble opinion :)
