### ISSUE TITLE
Default to motion state or normal state?

### ISSUE THREAD

**Issue by Ambrevar** [justbur/evil-ediff#8]
If I got it right, the motion state was made with special-derived modes in mind.  I find it ideal to make Info, help, package-menu, etc. a little more evil.

Why not ediff? If you press `s` you'll get a "buffer is read-only" error. Had it been in motion state, the key would have been unbound, which is cleaner in my opinion.

What do you think? What's the rule of thumb over the initial state and the special modes?

**Comment by justbur** [comment]
Sounds fine to me. Thanks
